= Review automation

Includes Schematron rules and customized terminology checker file (for Oxygen Author XML terminology checker plugin) for automated reviews of tech documentation in Oxygen Author XML.

For automated reviews using the Vale linter and lefthook (GitHub hook), see the https://github.hpe.com/eric-szegedi/vale_linter/wiki[vale linter repository].

When to use which review automation tool?

. What is the purpose of each review?
 
** Structure - Schematron and terminology checker plugin
 
** Style - Vale, terminology checker plugin
 
** Grammar - Vale, terminology checker plugin
+
NOTE: Schematron can be used for implementing style guides and grammar, but if you have too many rules it becomes unusable.

. What tool(s) will the review automation tool be integrated with?

** Oxygen Author XML - Schematron, terminology checker plugin, limited Vale styles via the terminology checker plugin

** VS Code - Vale

** Command Line - Vale (ex. vale file_1.dita)

** Git / GitHub - Vale through either GitHub actions or Git hooks
+
[NOTE] 
====
* GitHub actions need to enabled by writing this email address - scm_ghe_admins@groups.ext.hpe.com - to ask the admins to enable it for your repo.
 
* Git hooks can be used with the  https://github.hpe.com/eric-szegedi/vale_linter/wiki/Automating-Vale-linter-checks-with-lefthook[lefthook tool]
====